// FIX_ADD.v

// Generated using ACDS version 18.0 219

`timescale 1 ps / 1 ps
module FIX_ADD (
		input  wire [31:0] a0,     //     a0.a0
		input  wire [31:0] a1,     //     a1.a1
		input  wire        clk,    //    clk.clk
		input  wire [0:0]  en,     //     en.en
		output wire [31:0] result, // result.result
		input  wire        rst     //    rst.reset
	);

	FIX_ADD_altera_fxp_functions_180_4lk6zii fxp_functions_0 (
		.clk    (clk),    //   input,   width = 1,    clk.clk
		.rst    (rst),    //   input,   width = 1,    rst.reset
		.en     (en),     //   input,   width = 1,     en.en
		.a0     (a0),     //   input,  width = 32,     a0.a0
		.a1     (a1),     //   input,  width = 32,     a1.a1
		.result (result)  //  output,  width = 32, result.result
	);

endmodule
