// RAM_Resource_Test.v

// Generated using ACDS version 18.0 219

`timescale 1 ps / 1 ps
module RAM_Resource_Test (
		input  wire [95:0] data,    //  ram_input.datain
		input  wire [14:0] address, //           .address
		input  wire        wren,    //           .wren
		input  wire        clock,   //           .clk
		output wire [95:0] q        // ram_output.dataout
	);

	RAM_Resource_Test_ram_1port_180_jftw4ca ram_1port_0 (
		.data    (data),    //   input,  width = 96,  ram_input.datain
		.address (address), //   input,  width = 15,           .address
		.wren    (wren),    //   input,   width = 1,           .wren
		.clock   (clock),   //   input,   width = 1,           .clk
		.q       (q)        //  output,  width = 96, ram_output.dataout
	);

endmodule
