// FIX_MUL.v

// Generated using ACDS version 18.0 219

`timescale 1 ps / 1 ps
module FIX_MUL (
		input  wire [31:0] a,      //      a.a
		input  wire [31:0] b,      //      b.b
		input  wire        clk,    //    clk.clk
		input  wire [0:0]  en,     //     en.en
		output wire [63:0] result, // result.result
		input  wire        rst     //    rst.reset
	);

	FIX_MUL_altera_fxp_functions_180_ua7mybq fxp_functions_0 (
		.clk    (clk),    //   input,   width = 1,    clk.clk
		.rst    (rst),    //   input,   width = 1,    rst.reset
		.en     (en),     //   input,   width = 1,     en.en
		.a      (a),      //   input,  width = 32,      a.a
		.b      (b),      //   input,  width = 32,      b.b
		.result (result)  //  output,  width = 64, result.result
	);

endmodule
