// CTRL_START.v

// Generated using ACDS version 18.0 219

`timescale 1 ps / 1 ps
module CTRL_START (
		input  wire [0:0] data,    //  ram_input.datain
		input  wire [0:0] address, //           .address
		input  wire       wren,    //           .wren
		input  wire       clock,   //           .clk
		output wire [0:0] q        // ram_output.dataout
	);

	CTRL_START_ram_1port_180_uhhnf6q ram_1port_0 (
		.data    (data),    //   input,  width = 1,  ram_input.datain
		.address (address), //   input,  width = 1,           .address
		.wren    (wren),    //   input,  width = 1,           .wren
		.clock   (clock),   //   input,  width = 1,           .clk
		.q       (q)        //  output,  width = 1, ram_output.dataout
	);

endmodule
